spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  profiles:
  #    include: mysql

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      encoding: UTF-8

server:
  port: 8080
  error:
    include-message: always

# Swagger springdoc-ui Configuration
#springdoc:
#  packages-to-scan: com.test.demo
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: swagger-ui.html            # Swagger UI 경로 => localhost:8000/swagger-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true
